### PR TITLE
Version 3.0.0

### LINKED ISSUE #42: Need Unit Tests

### LINKED ISSUE #45: Update documentation on how to use the sample app

### LINKED ISSUE #143: How can I make this work for https secured server?
I tested it using http is seems ok,  then I switched to https server and is having WebSocket connection to 'wss://localhost:9856/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

Is there some special steps I need for https server?   Any tested example? Thanks.

### LINKED ISSUE #156: Drop node 4 support in CI jobs
Due to https://github.com/websockets/ws/releases/tag/5.0.0

### LINKED ISSUE #158: Investigate/implement `npm ci install` for CI
* https://docs.npmjs.com/cli/ci
* https://hackernoon.com/how-to-speed-up-continuous-integration-build-with-new-npm-ci-and-package-lock-json-7647f91751a

### LINKED ISSUE #169: Document fallback flag
Meant to catch this before releasing my apologies. Document what was added in #167.

### PR DESCRIPTION
**Pull request by alallier**
# Version 3.0.0

Consult [Migration Guide](MIGRATION_GUIDE.md) for help with updating from Version 2.x to 3.x

## Breaking/Removed

* Removed deprecated parameters (Reload no longer takes the server argument and will error if you provide it)
* Removed support for Node versions 4, 5, 6, 7, 8, and 9

## Breaking/Added

* Reload now returns a promise
    * Functions in the return API also return promises
        * `closerServer`
        * `startWebSocketServer`
    * Reload returns errors in promises

## Added

* Added unit tests. (See: https://github.com/alallier/reload/issues/42)
* Added coverage analyzer
    * Coverage 100% on `reload.js` file
* Added node 10 and 11 to the official supported list
* Added support for HTTPS
    * Cert and Key or PFX/P12
    * Note: This was available in version 1 and then was dropped in Version 2
* Added [sample app README](expressSampleApp/README.md) (See: https://github.com/alallier/reload/issues/45)
* Added [MIGRATION_GUIDE](MIGRATION_GUIDE.md) to help with migrating across major versions of reload
* Added force wss option
* CI jobs now use [npm ci isntall](https://docs.npmjs.com/cli/ci.html) (See: https://github.com/alallier/reload/issues/158)

## Changed

* Updates dependencies

## Closes the following issues:

* HTTPS - https://github.com/alallier/reload/issues/143 (Closes #143)
* Unit tests - https://github.com/alallier/reload/issues/42 (Closes #42)
* Document Fallback flag - https://github.com/alallier/reload/issues/169 (Closes #169)
* Drop Node 4 support - https://github.com/alallier/reload/issues/156 (Closes #156)
* Documentation on how to use sample app - https://github.com/alallier/reload/issues/45 (Closes #45)
* Use npm ci install - https://github.com/alallier/reload/issues/158 (Closes #158)

### CODE REVIEW

**Comment by lannonbr** [comment]
In the readme, it states to push a script tag down to the client as follows:

```html
<script src="/reload/reload.js"></script>
```

That said, it isn't too clear that "/reload/reload.js" is a route that reload sets up in the express app.

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! Any progress with this? Do you have any planned date for releasing 3.0.0?

**Comment by alallier** [comment]
@meszaros-lajos-gyorgy sorry this is taking so long, I just have to make a couple of tweaks and then get it out. I'll see if I can get it out in the next two weeks

**Comment by meszaros-lajos-gyorgy** [comment]
Thank you!

**Comment by alallier** [comment]
@meszaros-lajos-gyorgy in case you missed this. This is now merged and published to npm.

**Pull request merged**
