### PR TITLE
Unit tests for API (related to #42)

### PR DESCRIPTION
**Pull request by alallier**
* Cleaned up old test directory
* Enabled unit testing
* Wrote unit tests for API

(Related to #42)

### CODE REVIEW

**Comment by AckerApple** [comment]
I'm so glad you've gotten around to this task. I see you're getting a bunch of EADDRINUSE errors which eventually should bring about the desire to create an EADDRINUSE prompt or some handler to allow easier use of reload when an instance of reload is already running.

Good luck

**Comment by yamboy1** [comment]
@alallier Are we doing anything about this at the moment

**Comment by alallier** [comment]
@yamboy1 this uncovered a potential issue that I have not solved yet. Once I do that, this will move forward

**Comment by AckerApple** [comment]
You have to start a server beforeEach and close the server afterEach.

You'll have to ensure reload has close functionality.

My unit tests on ack-reload do the unit tests this way

**Comment by alallier** [comment]
Closing as this is really stale. I hope to finish this up soon

**Pull request closed without merging**
