### PR TITLE
If a directory is requested, check if index.html exists

### PR DESCRIPTION
**Pull request by amygrinn**
Also simplified the pathname.

### CODE REVIEW

**Comment by alallier** [comment]
Thanks for the PRs, I hopefully should have some time this week to check them out

**Comment by alallier** [comment]
@taylorgrinn can you describe what you were trying to do here? Reload always watches a directory and attempts to open the index.html by default if an alternative start page is not defined in the command line options

**Comment by cekvenich2** [comment]
@alallier This is common issue for dev.
This works:
http://154.12.250.248:8080/desEx/index.html
This does not:
http://154.12.250.248:8080/desEx
http://154.12.250.248:8080/desEx/

In production, we would not want to have index.html, we have just the url w/ 'real' http server. So development nav using reload CLI and product nav is not same. A work around is not to use the CLI but write your own dev server. Ideally, I can just use the CLI.

**Comment by alallier** [comment]
Closing in favor of #326

**Pull request closed without merging**
