### PR TITLE
Add support for port 443

### PR DESCRIPTION
**Pull request by yamboy1**
A modified version of @superhawk610's Pull Request #128 that automatically adds `:443` if a `https` is used rather that a `http`.

### CODE REVIEW

**Comment by yamboy1** [comment]
@superhawk610 Does this look okay?

**Comment by superhawk610** [comment]
I don't have access to a HTTPS server to test but the logic looks sound, assuming 443 is an anonymous port and behaves the same way as 80.

**Comment by alallier** [comment]
I was thinking about this PR. It shouldn't be needed after thinking about it. When using reload in command line mode we only create a `http` server not `https`. So we will never have to account for port 443. Of course the user could always specify port 443 in either express or command line mode and the port will be assigned based on that. The case that this PR account for should never hit

**Comment by yamboy1** [comment]
Closing due to @alallier's comment

**Pull request closed without merging**
