### PR TITLE
Add support for koa through an option

### LINKED ISSUE #15: koa
Consider adding support for koa?

### PR DESCRIPTION
**Pull request by nahtnam**
If you are using koa, the code would look something like this:

```javascript
const koa = require('koa');
const http = require('http');
const app = new koa();
const reload = require('reload');

const server = http.createServer(app.callback());
reload(server, app, false, { koa: true })
server.listen(3000);
```

Resolves #15.

### CODE REVIEW

**Comment by alallier** [comment]
Looks good haven't tested or anything yet though. Do you mind doing the following things:

* Creating a sample app and creating a new folder for it like `koaSampleApp`. This will help people in the future and myself too for testing.
* Can we you also target the `v2.0.0` branch?

I am also currently working on #77 for version 2, so don't be alarmed when I accepted this and modify how the koa option is handled.

**Comment by nahtnam** [comment]
Added an example app, unsure how to target the 2.0 branch.

Is it cool for me to add myself to the contributors section?

**Comment by yamboy1** [comment]
see [changing the base branch of a pull request](https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/)

**Comment by yamboy1** [comment]
Also, to fix the Travis CI build, get rid of the semicolons on lines 17, 20 and 24. See [https://standardjs.com/rules.html#semicolons](https://standardjs.com/rules.html#semicolons) for more information. Also, you can see if there are any standardjs errors by running `npm test` in your command line/terminal.

**Comment by alallier** [comment]
As a warning though changing the base of the branch might cause a merge conflict as v2.0.0 is ahead of master

**Comment by nahtnam** [comment]
Looks like things are pretty different for v2.0. Ill implement koa tonight.

**Comment by alallier** [comment]
Version 2.0 branch is now merged into master. So after some more tweaks and decision related to version 2, this diff isn't too bad now. Just have to clean up the merge conflict and tweak some things for the changes introduced by version 2. @nahtnam are you still up to working on this? Let me know either way so I can take the appropriate actions.

**Comment by alallier** [comment]
Going to close but keep for reference for when we go to implement this. Thanks for the initial work on this @nahtnam

**Pull request closed without merging**
